version: '3.7'

services:
  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    depends_on:
      - db
    command: python manage.py runserver -h 0.0.0.0 -p 5000
    volumes:
      - ./services/app/app/migrations:/usr/src/app/migrations
    ports:
      - "5000:5000"
    env_file:
      - ./services/app/dev.env

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    volumes:
      - psql_volume:/var/lib/postgresql/data/
    env_file:
      - ./services/db/dev.env
    stop_grace_period: 10s
    expose:
      - 5432

volumes:
  psql_volume: